CollapseMultipleEdges
digraphs/Digraphs pull request #333
Opened 2020-08-12 16:33 UTC by marinaanagno

2020-08-17 19:28 UTC, samanthaharper commented
An example of the difference in time between the two functions. 

`gap> D := RandomMultiDigraph(10000);
<immutable multidigraph with 10000 vertices, 35859826 edges>
gap> DIGRAPHS_CollapseMultipleEdges(D);; time;
24409`

`gap> DIGRAPHS_CollapseMultiColouredEdges(D, fail);; time;
105996`

2020-09-02 14:47 UTC, le27 approved these changes
Everything seems good to me :)

2020-09-06 16:08 UTC, marinaanagno commented on gap/isomorph.gi
> +      if Length(adjv) > 0 then
Thanks @le27 just deleted the unnecessary if statement :)

2020-10-07 12:37 UTC, james-d-mitchell commented
Resolves Issue #306

2020-10-14 13:59 UTC, james-d-mitchell requested changes
A couple of minor things to fix, then you're done!

2020-10-14 15:20 UTC, james-d-mitchell commented
Looks like the CI is failing because something in the C code for clique finding is broken. I.e. this PR is not responsible for the failing tests.

2020-11-16 16:46 UTC, james-d-mitchell commented on gap/isomorph.gi
> +  p, run, cur, range, cols, C, v, i, nbs;
```suggestion
  p, run, cur, range, cols, v, i, nbs;
```

2020-11-18 10:12 UTC, james-d-mitchell commented on gap/isomorph.gi
> +    for cols in new_cols do
```suggestion
  for cols in new_cols do
```

2020-11-18 10:12 UTC, james-d-mitchell commented on gap/isomorph.gi
> +      for i in [1 .. Length(cols)] do
```suggestion
    for i in [1 .. Length(cols)] do
```

2020-11-18 10:12 UTC, james-d-mitchell commented on gap/isomorph.gi
> +        cols[i] := Position(new_cols_set, cols[i]);
```suggestion
      cols[i] := Position(new_cols_set, cols[i]);
```

2020-11-18 10:13 UTC, james-d-mitchell commented on gap/isomorph.gi
> +      od;
```suggestion
    od;
```

2020-11-18 10:13 UTC, james-d-mitchell commented on gap/isomorph.gi
>      od;
```suggestion
  od;
```

2020-11-18 10:13 UTC, james-d-mitchell commented on gap/isomorph.gi
> +  end);
```suggestion
end);
```

2020-11-18 10:13 UTC, james-d-mitchell commented on gap/isomorph.gi
> +    return [Digraph(out), new_cols, mults];
```suggestion
  return [Digraph(out), new_cols, mults];
```

2020-11-18 10:15 UTC, james-d-mitchell submitted a review, later dismissed
There were a couple of minor things to fix, over indented lines etc, I just committed fixes for those, and otherwise I am happy with this.

2020-11-18 10:19 UTC, marinaanagno commented
Thanks for reviewing this @james-d-mitchell !

2020-11-18 14:41 UTC, wilfwilson commented
Does this have some usefulness/relation to `DigraphRemoveAllMultipleEdges`? Should `DigraphRemoveAllMultipleEdges` perhaps use this new function as its backend? Just an idea, haven't thought about it beyond writing this sentence.

2020-11-18 16:35 UTC, james-d-mitchell approved these changes
Looks good to me!

2020-11-18 16:37 UTC, james-d-mitchell commented
> Does this have some usefulness/relation to `DigraphRemoveAllMultipleEdges`? Should `DigraphRemoveAllMultipleEdges` perhaps use this new function as its backend? Just an idea, haven't thought about it beyond writing this sentence.

So, this solves a different issue that the one solved by `DigraphRemoveAllMultipleEdges` it replaces multiple edges between the same nodes by single edges with a colour, and is used inside the canonical labelling stuff. I think it's also slower than `DigraphRemoveAllMultipleEdges`.

2020-11-18 16:38 UTC, merged