ContractEdge
digraphs/Digraphs pull request #512
Opened 2021-11-03 16:00 UTC by hrj4

2021-11-03 21:58 UTC, wilfwilson commented on gap/oper.gi
> +    ErrorNoReturn("there must be an edge between ",src," and ",ran);
```suggestion
  elif not ([src, ran] in DigraphEdges(D)) then
    ErrorNoReturn("there must be an edge between ", src, " and ", ran);
```

2021-11-03 22:15 UTC, wilfwilson requested changes

2021-11-03 22:15 UTC, wilfwilson commented on gap/oper.gi
> +  elif not (IsPosInt(src) and src in DigraphVertices(D)) then
Given the filter of this method, `src` and `ran` are guaranteed to be positive integers, so I will remove this check. In any case, if `src` ever wasn't a positive integer, then it wouldn't be a member of `DigraphVertices(D)`, and so there still wouldn't be a need to check whether it was a positive integer first.
```suggestion
  elif not src in DigraphVertices(D) then
```

2021-11-03 22:15 UTC, wilfwilson commented on gap/oper.gi
> +  elif not (IsPosInt(ran) and ran in DigraphVertices(D)) then
```suggestion
  elif not ran in DigraphVertices(D) then
```

2021-11-03 22:15 UTC, wilfwilson commented on gap/oper.gi
> +  elif not ([src, ran] in DigraphEdges(D)) then
For a single edge, the following should be much more efficient (it typically avoids having to construct the whole set of edges from the list of out-neighbours).
```suggestion
  elif not IsDigraphEdge(D, src, ran) then
```

2021-11-03 22:15 UTC, wilfwilson commented on doc/oper.xml
> +    does not define an edge of <A>digraph</A>.<P/>
This does not match the implementation: currently an error occurs in this situation. Which behaviour do you want?

2021-11-03 22:15 UTC, wilfwilson commented on gap/oper.gi
> +    ErrorNoReturn("there must be an edge between ", src, " and ", ran);
I think this should be more precise (currently is doesn't explicitly say which direction the edge should be)
```suggestion
    ErrorNoReturn("[<src>, <ran>] must be an edge of the digraph <D> ",
                  "(the 2nd, 3rd, and 1st arguments, respectively),");
```

2021-11-03 22:17 UTC, wilfwilson reviewed
Sorry, I forgot to say: thank you for this pull request, it'll be a nice feature to have! I just have a few suggestions/questions.

2021-11-04 14:37 UTC, hrj4 commented
Hi Wilf, thanks for reviewing the pull request and for flagging the parts needing improvement. Hopefully I've resolved the things which needed resolving now... I'm one of the VIP students this semester and this was my first attempt at implementing a new function so I appreciate the detailed explanations of what I could've done better.

2024-05-10 13:45 UTC, james-d-mitchell commented
This feature was included in #618, so I'm going to close this.

2024-05-10 13:45 UTC, closed without merging