DigraphCycleBasis
digraphs/Digraphs pull request #610
Opened 2024-02-02 21:01 UTC by Jun2M

Implemented "DigraphCycleBasis" operation under oper.gi with appropreate (hopefully) declaration in oper.gd.

2024-02-05 08:36 UTC, james-d-mitchell commented
@Jun2M please add tests that test every line you propose to add, these would go in tst/standard/oper.tst

2024-02-05 14:37 UTC, james-d-mitchell requested changes
There are a number of unrelated changes in this PR, can you please rebase it so that they disappear? Also there do appear to still be a number of untested lines, if you could add tests for those, that'd be great!

2024-02-05 14:37 UTC, james-d-mitchell commented on gap/oper.gi
> +{D, src, ran}
I'm not sure why these changes are in this PR, it looks like you might have had a slightly older version of Digraphs than the most up to date. Can you please rebase your changes onto the current main branch?

2024-02-05 14:37 UTC, james-d-mitchell commented on gap/oper.gi
> +{D, src, ran}
Same as above

2024-02-05 14:37 UTC, james-d-mitchell commented on gap/oper.gi
> +  map := {a, b} -> (a - 1) * n + b;
Same again, these changes aren't related to your PR

2024-02-12 11:53 UTC, james-d-mitchell requested changes
While this is a great first pull request, ticking many of the required boxes, it has some rather critical issues. Mainly, the follow general issues arise:

* it's not completely clear from the comments what algorithm you are trying to implement, or what the meaning of the output is;
* there are a number of lines that have unnecessarily high complexity (for example, every time you are doing `Position` you are doing a linear time lookup in the list of edges)
* there are a number of further minor issues with the code (some indicated in this review, but there are a few more)

It is probably best if we discuss in detail the algorithm you are trying to implement, and then review how best to do this in GAP during the meeting on Wednesday.

2024-02-14 15:04 UTC, Jun2M commented on doc/oper.xml
expand further

2024-02-14 16:24 UTC, Jun2M commented on doc/oper.xml
> +    of all <E>eulerian</E> subgraphs of the graph. A <E>cycle basis</E> is a
Expand further

2024-03-10 14:42 UTC, Jun2M commented
@james-d-mitchell The point of the extreme test was so that the 'codecov' would stop complaining that the 8GB warning is not covered by a test. (the actual test itself is pretty meaningless as it is trying to find the cycle basis for a complete graph). I have removed the extreme test. 
Except for ( the 8GB warning and the matrix initialisation for old version of GAP ) not being covered by the test, everything seems to be passing. (cygwin was not passing but it seems to have passed this time for some reason?) My understanding is that I can not add test for those above cases. Is that correct?

2024-03-11 14:53 UTC, james-d-mitchell commented on doc/oper.xml
> +    represents edges [1, 2], [1, 3] and [2, 3] i.e. cycle subgraph
```suggestion
    represents edges <C>[1, 2]</C>, <C>[1, 3]</C> and <C>[2, 3]</C> i.e. cycle subgraph
```

2024-03-11 14:53 UTC, james-d-mitchell commented on doc/oper.xml
> +    An eulerian subgraph without isolated vertices can uniquely be
```suggestion
    An eulerian subgraph without isolated vertices can be uniquely
```

2024-03-11 14:54 UTC, james-d-mitchell commented on doc/oper.xml
> +    between vertices 1, 2 and 3
```suggestion
    between vertices <C>1</C>, <C>2</C> and <C>3</C>
```

2024-03-11 14:54 UTC, james-d-mitchell commented on doc/oper.xml
> +    If <A>digraph</A> contains a loop, it will throw an error. If <A>digraph</A>
```suggestion
    If <A>digraph</A> contains a loop, this function will return an error. If <A>digraph</A>
```

2024-03-11 14:56 UTC, james-d-mitchell commented on doc/oper.xml
> +    contains multiple edges, only one of the edges will be considered.
```suggestion
    is a multi-digraph, then multiple edges incident to the same vertices are treated as a single edge by this function.
```

2024-03-11 14:56 UTC, james-d-mitchell commented on doc/oper.xml
> +    The first list contains the out-neighours that provides the ordering
```suggestion
    The first list returned contains the out-neighours that provides the ordering 
```

2024-03-11 14:56 UTC, james-d-mitchell commented on doc/oper.xml
> +    on the edges with the symmetric edges appearing only once.
```suggestion
    on the edges with the symmetric edges appearing only once;
```

2024-03-11 14:57 UTC, james-d-mitchell commented on doc/oper.xml
> +    It is <E>OutNeighbours(MaximalAntiSymmetricSubdigraph(G))</E>.
```suggestion
    these are the same as <E>OutNeighbours(MaximalAntiSymmetricSubdigraph(G))</E>. 
```

2024-03-11 14:57 UTC, james-d-mitchell commented on doc/oper.xml
> +    The second list contains the basis vectors of the cycle space of the
```suggestion
    The second list returned contains the basis vectors of the cycle space of the
```

2024-03-11 14:57 UTC, james-d-mitchell commented on doc/oper.xml
> +    is in the subgraph and 0 otherwise. In this function, the ordering of the
```suggestion
    is in the subgraph and <M>0</M> otherwise. In this function, the ordering of the
```

2024-03-11 14:58 UTC, james-d-mitchell commented on doc/oper.xml
> +    <E>OutNeighbours(MaximalAntiSymmetricSubdigraph(G))</E>.
```suggestion
    <C>OutNeighbours(MaximalAntiSymmetricSubdigraph(G))</C>. 
```

2024-03-11 14:58 UTC, james-d-mitchell commented on doc/oper.xml
> +    <Ref Oper="OutNeighbours"/>.
```suggestion
    and <Ref Oper="OutNeighbours"/>.
```

2024-03-11 14:58 UTC, james-d-mitchell commented on doc/oper.xml
> +    The first basis vector for complete digraph with 4 vertices shown below
```suggestion
    The first basis vector for the complete digraph with 4 vertices shown below 
```

2024-03-11 14:59 UTC, james-d-mitchell commented on doc/oper.xml
> +    space very natural.
```suggestion
    space very natural.<P/>
```

2024-03-11 14:59 UTC, james-d-mitchell commented on doc/oper.xml
> +    connected component of the graph.
```suggestion
    connected component of the graph. <P/>
```

2024-03-11 15:01 UTC, james-d-mitchell commented on doc/oper.xml
> +    The complexity of the main traversal of the graph is <M>O(m + n)</M> and
```suggestion
    This function performs a depth first traversal of the input digraph with complexity <M>O(m + n)</M> and
```

2024-03-11 15:05 UTC, james-d-mitchell commented on gap/oper.gi
> +    queue := [s];
What you've implemented here seems to be a stack not a queue, so I suggest renaming this variable accordingly.

2024-03-11 15:06 UTC, james-d-mitchell commented on gap/oper.gi
> +  # ToDo : In the case the Digraph package requires GAP 4.12 or over,
```suggestion
  # TODO : In the case the Digraph package requires GAP 4.12 or over,
```

2024-03-11 15:08 UTC, james-d-mitchell commented on gap/oper.gi
> +          Add(unusedEdges, [u, i, v, visited[v][1], visited[v][2]]);
Seems like `v` isn't used later, so please remove it, and adjust the later code too.

2024-03-11 15:09 UTC, james-d-mitchell commented on gap/oper.gi
> +          Add(unusedEdges, [u, i, v, visited[v][1], visited[v][2]]);
Same comment as below, remove `v` please

2024-03-11 15:09 UTC, james-d-mitchell commented on gap/oper.gi
> +  roots := [];
`roots` doesn't seem to be used for anything so, please remove it

2024-03-11 15:09 UTC, james-d-mitchell commented on gap/oper.gi
> +    Add(roots, s);
```suggestion
```

2024-03-11 15:14 UTC, james-d-mitchell commented on gap/oper.gi
> +  while ForAny(visited, x -> x = false) do
Why not just set `s := Position(visited, false);` above then replace this line with `while s <> fail`, then do `s := Position(visit, false, s);` as the final line in this while loop? This way you aren't traversing visited twice for every loop, and you are also not traversing the parts of visited that you've already traversed.

2024-03-13 09:00 UTC, merged

2024-03-13 09:00 UTC, james-d-mitchell commented
Excellent thanks very much @Jun2M !