Add DigraphContractEdge
digraphs/Digraphs pull request #618
Opened 2024-02-21 15:40 UTC by saffronmciver

Initial implementation of ContractEdge (see [Contract Edge Wikipedia Article](https://en.wikipedia.org/wiki/Edge_contraction); as discussed, this implementation should not create multiple edges). Mutable and Immutable methods exist for this. 

Edge labels should be handled if `DigraphRemoveEdge` were removing them, but this has not been tested yet because of this issue. 

Contract edge takes a non looping edge `(u, v)`, and contracts this into a single vertex `w`. The edge is removed, vertex labels are combined (in a list), and incident edges to `(u, v)` become incident to `w`. `MultiDigraphs` are not accepted into this function. If an edge `(v, u)` exists, this is also contracted (removed). 

Documentation has not been written yet (this is in progress).

2024-02-21 16:49 UTC, james-d-mitchell commented on gap/oper.gi
> +  w := vertices[Length(vertices)]; # w is the new vertix identifier
```suggestion
  w := vertices[Length(vertices)]; # w is the new vertex identifier 
```

2024-02-21 16:50 UTC, james-d-mitchell commented on gap/oper.gi
> +  w := vertices[Length(vertices)]; # w is the new vertix identifier
```suggestion
  w := vertices[Length(vertices)]; # w is the new vertex identifier 
```

2024-02-21 16:59 UTC, james-d-mitchell commented on gap/oper.gi
> +  if Length(edge) <> 2 then
Shouldn't this also check `IsDenseList`?  In case, the second entry of edge is bound but the first not.

2024-03-13 08:54 UTC, james-d-mitchell commented
@saffronmciver is this ready for review?

2024-03-13 15:27 UTC, mtorpey requested changes
Overall thoughts:
- `DigraphContractEdge` should always return a digraph, even if it's using mutability and just returning a pointer to the original thing.
- We should avoid copying digraphs in the mutable case.
- I see some code repeated in the mutable and immutable methods, e.g. the checks at the start.  Feel free to make another function that these can both call.  You can do this with the simple syntax `DIGRAPHS_SomeFunctionName := function(...) ... end;`
- The immutable method has a pattern where you make a graph and then add and remove things one at a time with `AddEdge` and so on.  It'd be better to do this with an immutable graph, and then do `MakeImmutable` just before returning, to avoid copying graphs again and again.

2024-03-14 09:37 UTC, james-d-mitchell commented on gap/oper.gi
> +    ErrorNoReturn("u, v is not an edge of D");
```suggestion
    ErrorNoReturn("expected an edge between the 2nd and 3rd arguments (vertices) ", u, " and ", v, " but found none");
```

2024-03-14 09:40 UTC, james-d-mitchell commented on gap/oper.gi
> +  if IsMultiDigraph(D) then  # multi digraphs cannot have their edges contracted
These checks should be combined into a single `if A then Error; elif B then Error;...` if you see what I mean

2024-03-14 09:41 UTC, james-d-mitchell commented on gap/oper.gi
> +    ErrorNoReturn("Cannot contract an edge for a MultiDigraph");
Also the error messages should follow the same format as everywhere else in the package:

> the 1st argument (a digraph) must not have multiple edges

2024-03-14 09:42 UTC, james-d-mitchell commented on gap/oper.gi
> +    ErrorNoReturn("Cannot contract an edge with the same source and range");
Similarly this error message should be revised.

2024-03-14 09:47 UTC, james-d-mitchell requested changes
This looks pretty good for a first PR, thanks! Handling the edge/node labels is much more complicated than I expected, looks like you've done a pretty thorough job. Please make the changes indicated by @mtorpey and me, and then we'll have another look!

2024-03-14 09:47 UTC, james-d-mitchell commented on gap/oper.gi
> +                                     # the new digraph
Or even `NullDigraph(0);`!

2024-03-14 09:47 UTC, james-d-mitchell commented on gap/oper.gi
> +  copy := DigraphImmutableCopy(D);  # create a copy of the original digraph,
If `D` doesn't have edge or vertex labels, then this copy is unnecessary, we should just return `D` right away here without doing anything extra. 

Also: even if `D` does have edge and/or vertex labels, then we don't really require the copy of `D` but only of its edge and/or vertex labels, and even then probably only the labels of the vertices or edge incident to the edge being collapsed. I think this should be updated to copy only the very least amount of data from `D` required.

2024-03-28 09:19 UTC, james-d-mitchell commented
I've just rebased this onto main which will hopefully fix the CI.

2024-03-28 10:56 UTC, james-d-mitchell commented
Closing and re-opening to trigger ci

2024-04-05 15:42 UTC, mtorpey approved these changes
This is a big improvement, and I think it's now ready for merging.  All my comments have been addressed, and it looks to me like all of @james-d-mitchell's too.

Recommend merging.

2024-04-17 08:16 UTC, merged

2024-04-17 08:16 UTC, james-d-mitchell commented
Thanks @saffronmciver !