Dreadnaut support
digraphs/Digraphs pull request #651
Opened 2024-05-26 18:16 UTC by pramothragavan

Broadly speaking, a dreadnaut file starts with "configuration" information about the graph, such as the number of vertices (denoted by 'n'), the start index for vertex numbering (denoted by '$') and whether or not a graph is a digraph (denoted by the presence of 'd').  The configuration section always ends with a 'g'. The rest of the file gives information concerning individual vertices in the form of adjacency lists. For example:

n=2
$=1
d
g
1: 1 2;
2: 2;

would represent a 1-indexed digraph with 2 vertices with edges {1,1}, {1,2}, {2,2}.

General overview:

- `DIGRAPHS_ParseDreadnautConfig` aims to get values for either '$' (which indicates the start index for vertex numbering) or 'n' (which indicates the number of vertices). Note that '$' defaults to 0 and that I chose to reindex all graphs such that vertex numbering starts at one (which I think is convention for the Digraphs package?)
-  `DIGRAPHS_LegalDreadnautEdge` aims to filter out illegal edges and throws an error if an edge is illegal. An example of an illegal edge might be a loop for an undirected graph or an edge containing a vertex that is not allowed within the constraints of the values of '$' and 'n'. (In the case of illegal edges, nauty throws a warning message and then ignores the edge so I was trying to replicate this behaviour).
- `DIGRAPHS_SplitDreadnautLines` effectively takes a line of dreadnaut (e.g. "1: 2 3 5; 4: 2 1 3; 2: 3;") and aims to split this into parts which are to be handled individually (in this case the parts would be ["1: 2 3 5;", "4: 2 1 3;", "2: 3;"]). The idea here is that although usually these parts would each be on their own line, it's techincally fine for some or all of them to share a line (with or without a semicolon) so I thought it made more sense to condense everything onto one line and then split into parts. There are various auxiliary commands that can be used within the dreadnaut format alongside the definition of the graph (more info [here](https://pallini.di.uniroma1.it/nug28.pdf#page=6)) which I mostly chose to neglect, with the exception of 'f' which defines a partition of vertices. Note that '$$' at the end of a file means reindex the graph to start counting at 0 (which I ignored).
- `DIGRAPHS_ParseDreadnautGraph` intends to parse the non-configuration part of the file, which has been split into parts after being fed through to `DIGRAPHS_SplitDreadnautLines`

2024-05-29 08:15 UTC, james-d-mitchell requested changes
Generally speaking this looks really good! I've added a few comments, mostly about the adding some details to the error messages if possible. Some general comments:

* it'd be great if the error messages could report in what line of the file the error occurs, I think we discussed this, but don't exactly remember the outcome of this. One approach would be to store the original file contents in a variable, and then search within that for the part that causes the error. I'm not sure if this would actually work or not, just a thought.
* in the PR description you mention:

> Note that '$' defaults to 0 and that I chose to reindex all graphs such that vertex numbering starts at one (which I think is convention for the Digraphs package?)

this sounds appropriate, and yes this is the convention (really more a requirement in Digraphs, i.e. at present it's only possible to have digraphs with vertices `[1 .. n]` for some `n`). It'd be best if the code at the very least issued a warning when you are renumber the vertices, to avoid violating the principal of least astonishment (i.e. try to read a graph with nodes not `[1 .. n]`, then silently getting a graph with nodes `[1 .. n]` would be surprising, so better issue a warning that this is happening). It'd also be useful to have the original vertices as labels in the newly constructed digraph, so if for example the graph has 0-indexed vertices, then the labels of the vertices in the output graph would be set using `DigraphSetVertexLabels(D, [0 .. n - 1]);` (if this is the correct mapping). 
* You mention in a couple of other places in the PR description that your code potentially ignores some other parts of dreadnaut files, if you detect parts that are ignored for whatever reason then, please issue a warning for each of these too, again to avoid surprising the user. 
* Have you checked how good the code coverage of your tests is? Given the number of lines of code in the implementation versus the number of lines of tests, I'm guessing that there's maybe some work to do there. I've sent you a python script by email that you can use to check the code coverage, just run `./code-coverage-test-gap.py tst/standard/io.tst` inside the digraphs directory.

2024-05-29 08:15 UTC, james-d-mitchell commented on gap/io.gi
> +    ErrorNoReturn("cannot open the file given as the 1st argument <name>,");
Please include the file name in the error message.

2024-05-29 08:15 UTC, james-d-mitchell commented on gap/io.gi
> +    ErrorNoReturn("cannot open the file given as the 1st argument <name>,");
Same again include the file name in the error message.

2024-05-29 14:56 UTC, james-d-mitchell commented on gap/io.gi
> +        continue;
```suggestion
```

2024-05-30 08:43 UTC, james-d-mitchell commented
@pramothragavan please let me know when you think this is ready again, and thanks !

2024-05-30 09:37 UTC, pramothragavan commented
> @pramothragavan please let me know when you think this is ready again, and thanks !

Will do!

2025-01-28 15:15 UTC, mtorpey commented
Hi @pramothragavan!  Looking forward to hopefully seeing you soon for the new VIP.

What state did this Dreadnaut project get to?  Would it be a good thing for you to get back into this semester if there's work still to do on it?

2025-01-28 16:22 UTC, pramothragavan commented
Hi — there are definitely some kinks to be dealt with, but I think it would be a good place to start!

> On 28 Jan 2025, at 15:15, Michael Young ***@***.***> wrote:
> 
> 
> Hi @pramothragavan <https://github.com/pramothragavan>! Looking forward to hopefully seeing you soon for the new VIP.
> 
> What state did this Dreadnaut project get to? Would it be a good thing for you to get back into this semester if there's work still to do on it?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/digraphs/Digraphs/pull/651#issuecomment-2619293665>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AZXCLQY4AOD2PKUEJQWZQVT2M6NI5AVCNFSM6AAAAABIJ72E4SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMJZGI4TGNRWGU>.
> You are receiving this because you were mentioned.
>

2025-02-08 18:41 UTC, pramothragavan commented
This is a significant overhaul on previous versions -- `WriteDreadnautGraph` is untouched, but the decoder has been completely rewritten.

As @james-d-mitchell suggested, I've taken the parser used in the dreadnaut program and effectively rewritten it in GAP. The original C code uses a stream to parse character by character. GAP has a Stream object, but this lacks some of the functionality needed, so I created a record called `Stream` that aligns GAP's streams with how they're used in C. Other helper functions I've added:

- `DIGRAPHS_GETNWC` finds the next character in the stream that is not in `" ,\t"`
- `DIGRAPHS_GETNWL` finds the next character in the stream that is not in `" \n\t\r"`
- `DIGRAPHS_readinteger` reads integers from the stream (i.e. avoiding issues with reading `"10"` as opposed to `"1"` and `"0"` that might arise when parsing character by character)
- `DIGRAPHS_GetInt` also reads the next integer from the stream. There are some instances where dreadnaut allows for an optional `'='` character (e.g. `n=2` is the same as `n2`). This function ignores any `'='` characters and then calls `DIGRAPHS_readinteger`. 
- `DIGRAPHS_readgraph` parses the graph's adjacency data
- `DIGRAPHS_ParsePartition` is used to parse a partition, if given. The partition is stored using vertex labels.

Documentation for various commands is given [here](https://pallini.di.uniroma1.it/nug28.pdf#page=6)  (pages 6-12). Many of these are used to manipulate the graph and I have focused on supporting commands more closely tied to directly defining the graph. 

For now, I need to write (many) tests but I'm also interested if there are any commands that you'd like to see support for. I'm happy to implement anything really, but didn't want to waste time on things you didn't want. The commands that I am currently supporting are:

- All of those mentioned in section (A) of the above link. In dreadnaut, these would just define the mode which dreadnaut is using. This is important for subsequent use of nauty/traces, but is irrelevant for actually reading in the graph so this is just ignored.
- From section (B): `n=#`, `g` (and all subcommands), `_`, `__`
- From section (C): `f`
- From section (D): `$=#`, `$$`, `+`, `d, -d`
- From section (F): `"..."`, `!`, `q`

I think a couple of the unsupported commands from (B) might be worth looking into. Anything unsupported currently should raise an InfoWarning, with the exception of `<`, `>`, `e` (these three relate to reading in, outputting and editing graphs) which raise `ErrorNoReturn`.

2025-02-12 20:39 UTC, james-d-mitchell commented on gap/io.gi
> +        res := Int([char]);
```suggestion
        res := IntChar(char);
```

2025-02-12 20:41 UTC, james-d-mitchell commented on gap/io.gi
> +        res := res * 10 + Int([char]);
```suggestion
        res := res * 10 + IntChar(char);
```

2025-02-19 15:56 UTC, james-d-mitchell reviewed
Some comments delivered verbally, this looks really good, just some minor things to do.

2025-02-19 15:56 UTC, james-d-mitchell commented on gap/io.gi
> +        res := Int([char]);
Ah ok my bad, happy with how it is

2025-02-19 15:56 UTC, james-d-mitchell commented on gap/io.gi
> +                  "on line ", r.newline);
```suggestion
                   "on line ", r.newline);
```

2025-02-19 15:56 UTC, james-d-mitchell commented on gap/io.gi
> +                    Info(InfoWarning, 1, "Ignoring illegal edge (",
You might consider using `StringFormatted` to make this easier to digest.

2025-02-26 02:03 UTC, pramothragavan commented
#485 I think this is basically complete, but I don't really like some of the behaviour with `ReadDigraphs`. As @james-d-mitchell requested verbally, I've implemented the hashsets `WholeFileEncoders` and `WholeFileDecoders`, which currently only contain `WriteDreadnautGraph` and `ReadDreadnautGraph` respectively, but is a bit more futureproof than the current implementation (hopefully DIMACS can also feature in `ReadDigraphs`?). There are also corresponding functions `IsWholeFileEncoder` and `IsWholeFileDecoder`, but I'm not sure where the documentation for this is meant to go.

Initially, the idea was that we need to handle whole file decoders separately to single line decoders in `ReadDigraphs`. However, it transpires that if multiple graphs were given in a .dre file, dreadnaut would just read in the last one (effectively overwriting the previous graph each time). This behaviour is mirrored by `ReadDreadnautGraph` (with an InfoWarning issued) and by extension `ReadDigraphs`, but this outcome feels unexpected.

I also think there is ambiguity as to whether you should specify `DigraphFromDreadnautString` or `ReadDreadnautGraph` as the optional decoder argument in `ReadDigraphs`. I think having two encoders/decoders might be overcomplicating things, especially given that `ReadDigraphs` could always be used instead of `ReadDreadnautGraph`. Same for writes.

2025-04-08 07:41 UTC, james-d-mitchell commented on doc/io.xml
> +        It supports loops but multiple edges will be ignored.  The format consists of an
```suggestion
        The format supports loops but multiple edges will be ignored.  The format consists of an
```

2025-04-08 08:02 UTC, james-d-mitchell requested changes
Looks good, some minor changes suggested, and then I'll be happy to merge. One thing that is less major: can you please use 2 spaces for indentation, rather than 4?

2025-04-08 08:02 UTC, james-d-mitchell commented on gap/io.gi
> +                      "  * A list of cells (e.g. 'f=[...]')",
Seems like the `\n` is missing here, but my comment is that I think error messages shouldn't have `\n` in them at all.

2025-04-08 09:03 UTC, pramothragavan commented on doc/io.xml
> +        vertices, the index origin for vertices, and whether the graph is directed. This is followed
Yeah it's exactly that. I'll change it to starting value for vertices

2025-04-08 09:05 UTC, pramothragavan commented on doc/io.xml
> +    If the vertices are not already 1-indexed, they will be reindexed accordingly.
They're not! But I'll add that in

2025-04-08 09:32 UTC, pramothragavan commented on doc/io.xml
> +    If non-default integer vertex labels are provided, they will be used to define the partition structure.<P/>
Ah so what I mean is that in GAP, if you create a digraph on n vertices, its vertex labels will be `[1 .. n]` (default integer vertex labels). If the given digraph has vertex labels different to `[1 .. n]` then (as long as the labels are integers), they will be used to define a partition. So, if the labels are `[1, 1, ..., 1]` in GAP then this would be converted into the partition `f = [1 2 .. n]` in dreadnaut (i.e. all vertices in the same part).

My intention was that if the labels in GAP are the default integer vertex labels, then the user wasn't trying to define a partition so no need to create one in dreadnaut (in dreadnaut the default partition is every vertex in the same part). But I'm now realising maybe the user might have intentionally set the vertex labels to `[1 .. n]` and wants this to inform a partition. I could raise a Y/N message about creating a partition in the case of default integer vertex labels? This might be annoying because it'd pop up most of the time, I imagine.

2025-04-08 09:32 UTC, pramothragavan commented on gap/io.gi
> +              in ["y", "yes"]) then
Think we're fine because we're doing `LowercaseString`?

2025-04-08 15:17 UTC, james-d-mitchell commented on doc/io.xml
> +    If non-default integer vertex labels are provided, they will be used to define the partition structure.<P/>
In some sense the less "magic" the better, be a good idea to simply add the partition as an argument to the function, then just it if present, and don't use it if not. Not completely sold on the y/n questions because this requires user intervention, so couldn't easily use it in code, if you see what I mean.

2025-04-08 15:59 UTC, pramothragavan commented on doc/io.xml
> +    If non-default integer vertex labels are provided, they will be used to define the partition structure.<P/>
Agreed, I think this is better. I suppose that if the user wanted to write to a file using `WriteDigraphs`, it wouldn't be possible to include a partition? I'm happy to let this slide and maybe just add a note in the doc saying they could use a combination of `DreadnautString` and `IO_Write` to achieve that result. If you think that sounds good, I'll implement it and hopefully wrap this up!

2025-04-09 06:49 UTC, james-d-mitchell commented on doc/io.xml
> +    If non-default integer vertex labels are provided, they will be used to define the partition structure.<P/>
> Agreed, I think this is better. I suppose that if the user wanted to write to a file using `WriteDigraphs`, it wouldn't be possible to include a partition? I'm happy to let this slide and maybe just add a note in the doc saying they could use a combination of `DreadnautString` and `IO_Write` to achieve that result.
> 
> ^ I've just implemented this, so hopefully we're all good @james-d-mitchell

Sounds good to me.

2025-04-09 06:53 UTC, james-d-mitchell commented on gap/io.gi
> +    if NameFunction(file!.coder) in WholeFileEncoders and file!.mode <> "w" then
One final comment, can you make this y/n choice optional please? For the same reason as elsewhere, it will be impossible to use this in code if user input is required, best to have a flag/option something that disables this behaviour. If that is too hard to achieve within the current framework, then maybe the best thing to do is just to issue the info warning, but remove the proceed check?

2025-04-09 06:54 UTC, james-d-mitchell commented on gap/io.gi
> -      malformed_file();
Sorry also: why did you make this change please? In particular, where is `file` now closed?

2025-04-09 09:59 UTC, pramothragavan commented on gap/io.gi
> +    if NameFunction(file!.coder) in WholeFileEncoders and file!.mode <> "w" then
Yeah I agree it's not ideal, but I think user could avoid this behaviour by specifying ``mode="w"`` when they're using a whole file encoder.  So, ``WriteDigraphs(filename, D, WriteDIMACSDigraph, "w")`` wouldn't run into this issue. In general ``mode`` defaults to ``"a"`` so I felt the need to warn before doing something destructive. Maybe it'd be better to change to infowarning to

```
      Info(InfoWarning, 1, NameFunction(file!.coder), " is a whole file ",
           "encoder and so the argument <mode> is defaulting to \"w\". This ",
           "will overwrite any current file contents. (This warning can be avoided by",
           "specifying the argument <mode> as \"w\".) Continue (Y/N)?");
```

2025-04-09 10:02 UTC, james-d-mitchell commented on gap/io.gi
> +    if NameFunction(file!.coder) in WholeFileEncoders and file!.mode <> "w" then
It's more the issue that user input is required that I'm concerned about. Could we maybe just refuse to write if "a" is passed as the mode? I.e. forbid "a" when using whole file decoders? The info warning can then be an error?

2025-04-09 10:13 UTC, pramothragavan commented on gap/io.gi
> -      malformed_file();
So I think the idea is that you could either reach this point by using ``ReadDigraphs``, ``ReadDIMACSDigraph`` or ``DigraphFromDIMACSString``. In the third case, there wouldn't be a file to close so we wouldn't want any file closing logic in this function. For the first two cases, file closing should be handled by ``ReadDigraphs`` here:

https://github.com/digraphs/Digraphs/blob/54ea602693573b6c2f525be5d31265bd5208e2c5/gap/io.gi#L643-L645

2025-04-09 10:16 UTC, pramothragavan commented on gap/io.gi
> +    if NameFunction(file!.coder) in WholeFileEncoders and file!.mode <> "w" then
Yeah cool that makes sense

2025-04-09 10:24 UTC, james-d-mitchell approved these changes

2025-04-09 10:24 UTC, james-d-mitchell commented on gap/io.gi
> -      malformed_file();
Sounds good!

2025-04-09 11:37 UTC, merged

2025-04-09 15:51 UTC, pramothragavan commented on gap/io.gi
> -      malformed_file();
Sorry I've messed up here and then to make things worse I've managed to convince you that it was fine. You're right that if we're reading in malformed files for a whole file decoder then there was nothing in place to close these files. PR #757 addresses this. 

What's more, there's an underlying issue with `WriteDigraphs`. Regardless of file format, if the string encoder raises an error, there's nothing in place to close the file. I'm not really sure how to fix this, but there's more info in the PR. Sorry that this is coming after the merge

2025-04-09 18:40 UTC, james-d-mitchell commented
No worries @pramothragavan it happens! I could also have checked before merging. Looks like you have a fix in the works, which is great!